from com.bridgelab.util.LinkedList import LinkedList

obj = LinkedList()
# obj.sort(30)
# obj.sort(50)
# obj.sort(80)
# obj.sort(230)
# obj.sort(5)
obj.sort(6)
obj.sort(4)
obj.display()

print(obj.poll_last())
print("After poll last")
obj.display()
print(obj.poll_last())
# print(obj.search(55))
# print("Size : ", obj.size())
# print("remove operation : ")
# obj.remove(4)
obj.display()
